# Project information
site_name: 算法笔记
site_author: huihui
site_description: 结合leetcode刷题记录，整理汇总 刷leetcode算法合集，包含可运行、调试的vscode工程
docs_dir: build
# Repository
repo_name: lifei098909/hello-algo
repo_url: https://github.com/lifei098909/Alg-note
